server:
  port: 8080
spring:
  application:
    name: "notification"
#  profiles:
#    include: "local"
  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    ssl:
#      enabled: true
    addresses: "amqp://guest:guest@localhost:5672"
    virtual-host: /
    listener:
      simple:
        concurrency: 1
    template:
      retry:
        enabled: true
        initial-interval: 5s
        maxAttempts: 3
        maxInterval: 10s
        multiplier: 2
    queue:
      prueba: "cola-de-prueba"
    exchange:
      prueba: "prueba"
    routing-key:
      prueba: "routing-key"
